name: Deploy VLESS
on:
  workflow_dispatch:
    inputs:
      sso_url:
        description: 'SSO Link'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests tf-playwright-stealth
          playwright install --with-deps chromium

      - name: Run Playwright Script
        env:
          SSO_URL: ${{ github.event.inputs.sso_url }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python run_deploy.py
